#!/usr/bin/env python3
"""Rubbing out the page: a zigzag eraser stroke, grown over N stepped frames.

Writes rub.svg (a horizontal sprite of N mask frames, the last one fully erased)
and rub.css (the view transition that steps through the sprite, with the rubber
riding the end of the stroke on the same stops).
usage: ./gen-rub.py
"""
from math import hypot
from pathlib import Path

N = 36          # frames, 20fps over DUR: steady enough for the rubber to read as one hand
DUR = 1.8       # seconds
ROWS = 7        # back-and-forth passes, top to bottom
WIDTH = 24      # stroke width, in the 100x100 frame

here = Path(__file__).parent
ROOT = here.parent.parent  # the repo: this script lives in design/ink

# zigzag from top left to bottom right, overshooting the sides so the ends are clean
pts = []
for r in range(ROWS):
    y = 3 + r * (97 / (ROWS - 1))
    pts += [(-8, y), (108, y + 4)] if r % 2 == 0 else [(108, y), (-8, y + 4)]

seg = [hypot(b[0] - a[0], b[1] - a[1]) for a, b in zip(pts, pts[1:])]
total = sum(seg)


def at(f):
    """Point a fraction f of the way along the stroke."""
    d = f * total
    for (a, b), s in zip(zip(pts, pts[1:]), seg):
        if d <= s:
            t = d / s
            return a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t
        d -= s
    return pts[-1]


path = "M" + " L".join(f"{x:g} {y:g}" for x, y in pts)
frames = []
for i in range(N):
    if i == N - 1:
        body = '<rect x="-10" y="-10" width="120" height="120"/>'
    else:
        f = (i + 1) / N
        body = (f'<path d="{path}" pathLength="1" stroke-dasharray="{f:.4f} 2" fill="none" '
                f'stroke="#000" stroke-width="{WIDTH}" stroke-linecap="round" stroke-linejoin="round"/>')
    frames.append(f'<svg x="{i * 100}" width="100" height="100" viewBox="0 0 100 100">'
                  f'<g filter="url(#fray)">{body}</g></svg>')

(ROOT / "src/assets/paper/rub.svg").write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {N * 100} 100" preserveAspectRatio="none">'
    '<filter id="fray" x="-10%" y="-10%" width="120%" height="120%">'
    '<feTurbulence type="fractalNoise" baseFrequency=".12" numOctaves="2" seed="4"/>'
    '<feDisplacementMap in="SourceGraphic" scale="3"/></filter>'
    + "".join(frames) + "</svg>\n")

# each frame holds for DUR/N; the rubber's worn end (.5rem, 3.6rem into it) sits at the end of the stroke so far
mask, rubber = [], []
for i in range(N):
    stop = f"{i / N * 100:.2f}%"
    mask.append(f"  {stop} {{ mask-position: {i / (N - 1) * 100:.3f}% 0; }}")
    x, y = at((i + 1) / N) if i < N - 1 else (115, 115)
    if i < N - 1:
        x = min(max(x, 3), 93)  # the stroke overshoots the edges; keep the rubber on the page
    tilt = -8 if i % 2 else 6
    rubber.append(f"  {stop} {{ transform: translate(calc({x:.1f}vw - .5rem), calc({y:.1f}vh - 3.6rem)) rotate({tilt}deg); }}")

(ROOT / "src/styles/rub.css").write_text(f"""/* generated by gen-rub.py: rubbing the page out into the other theme */
:root {{ --rub-duration: {DUR}; --rub-rows: {ROWS}; }}  /* read by theme.js for the sound */
::view-transition-old(root) {{ animation: none; }}
::view-transition-new(root) {{
  animation: rub {DUR}s steps(1, end) both;
  mix-blend-mode: normal;
  -webkit-mask: url("../assets/paper/rub.svg") 0 0 / {N * 100}% 100% no-repeat;
  mask: url("../assets/paper/rub.svg") 0 0 / {N * 100}% 100% no-repeat;
}}
@keyframes rub {{
{chr(10).join(mask)}
  100% {{ mask-position: 100% 0; }}
}}

/* the rubber, drawn on top of both pages, rides the end of the stroke */
::view-transition-old(rubber) {{ display: none; }}
::view-transition-new(rubber) {{ animation: none; }}
::view-transition-group(rubber) {{ animation: rubber {DUR}s steps(1, end) both; }}
@keyframes rubber {{
{chr(10).join(rubber)}
  100% {{ transform: translate(115vw, 115vh); }}
}}
""")
print(f"rub.svg + rub.css, {N} frames over {DUR}s")
